[package]
name = "ruosh"
version = "0.1.0"
authors = ["Steve Loveless <steve.loveless@gmail.com>"]

[dependencies]
readline = { git = "https://github.com/shaleh/rust-readline.git" }
ruru = "*"

[lib]
crate-type = ["dylib", "rlib"]
