[package]
name = "ruosh"
version = "0.1.0"
authors = ["Steve Loveless <steve.loveless@gmail.com>"]

[dependencies]
rustyline = "1.0.0"
ssh2 = "*"
thrussh_client = "*"
mrusty = "*"

[lib]
crate-type = ["dylib", "rlib"]
